[package]
name = "tiles3d"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
rapier3d = "0.26.1"
bevy_rapier3d = "0.30.0"
rand = "0.8"
ndarray = "0.15"
image = "0.24"
plotters = "0.3"
bevy_rich_text3d = "0.4.0"
serde = "1.0.219"
serde_json = "1.0.142"
futures-lite = "2.6.1"
